# fly.toml app configuration file generated for tensecondchallenge-white-morning-4012 on 2025-04-16T13:51:32-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tensecondchallenge-white-morning-4012'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 5005
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 2
